### ISSUE TITLE
AccessViolationException when using FastReport.DataVisualization.Charting.Chart in .netcoreapp3.1?

### ISSUE THREAD

**Issue by acpwrk1098** [FastReports/winforms-datavisualization#15]
FastReport.DataVisualization v2020.4.2
Win10
.netcoreapp3.1

If I build and debug the attached project (based on a HelloWorld-style Chart app - https://stackoverflow.com/a/10624227 )
[WindowsFormsApp1.zip](https://github.com/FastReports/winforms-datavisualization/files/5856856/WindowsFormsApp1.zip)
then I'm seeing an AccessViolationException 0xc0000005

If you replace FastReports.DataVisualization with https://www.nuget.org/packages/System.Windows.Forms.DataVisualization/1.0.0-prerelease.19212.2 then it works OK

**Comment by KirillKornienko** [comment]
Hello! I researching this problem
